---
galaxy_info:
    author: Amr
    description: Ansible role to deploy T-Shirt Customizer app
    company: AmrSapience
    license: MIT
    min_ansible_version: 2.13

    platforms:
        - name: MacOSX
          versions:
              - all

    galaxy_tags:
        - deployment
        - nodejs
        - sftp

dependencies: []
